"""empty message

Revision ID: a65d04526184
Revises: 
Create Date: 2021-03-09 21:17:46.896122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65d04526184'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.String(length=10), nullable=True),
    sa.Column('radius_mean', sa.Float(), nullable=True),
    sa.Column('texture_mean', sa.Float(), nullable=True),
    sa.Column('perimeter_mean', sa.Float(), nullable=True),
    sa.Column('area_mean', sa.Float(), nullable=True),
    sa.Column('smoothness_mean', sa.Float(), nullable=True),
    sa.Column('compactness_mean', sa.Float(), nullable=True),
    sa.Column('concavity_mean', sa.Float(), nullable=True),
    sa.Column('concave_points_mean', sa.Float(), nullable=True),
    sa.Column('symmetry_mean', sa.Float(), nullable=True),
    sa.Column('fractal_dimension_mean', sa.Float(), nullable=True),
    sa.Column('radius_se', sa.Float(), nullable=True),
    sa.Column('texture_se', sa.Float(), nullable=True),
    sa.Column('perimeter_se', sa.Float(), nullable=True),
    sa.Column('area_se', sa.Float(), nullable=True),
    sa.Column('smoothness_se', sa.Float(), nullable=True),
    sa.Column('compactness_se', sa.Float(), nullable=True),
    sa.Column('concavity_se', sa.Float(), nullable=True),
    sa.Column('concave_points_se', sa.Float(), nullable=True),
    sa.Column('symmetry_se', sa.Float(), nullable=True),
    sa.Column('fractal_dimension_se', sa.Float(), nullable=True),
    sa.Column('radius_worst', sa.Float(), nullable=True),
    sa.Column('texture_worst', sa.Float(), nullable=True),
    sa.Column('perimeter_worst', sa.Float(), nullable=True),
    sa.Column('area_worst', sa.Float(), nullable=True),
    sa.Column('smoothness_worst', sa.Float(), nullable=True),
    sa.Column('compactness_worst', sa.Float(), nullable=True),
    sa.Column('concavity_worst', sa.Float(), nullable=True),
    sa.Column('concave_points_worst', sa.Float(), nullable=True),
    sa.Column('symmetry_worst', sa.Float(), nullable=True),
    sa.Column('fractal_dimension_worst', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_data_area_mean'), 'diagnosis_data', ['area_mean'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_area_se'), 'diagnosis_data', ['area_se'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_area_worst'), 'diagnosis_data', ['area_worst'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_compactness_mean'), 'diagnosis_data', ['compactness_mean'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_compactness_se'), 'diagnosis_data', ['compactness_se'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_compactness_worst'), 'diagnosis_data', ['compactness_worst'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_concave_points_mean'), 'diagnosis_data', ['concave_points_mean'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_concave_points_se'), 'diagnosis_data', ['concave_points_se'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_concave_points_worst'), 'diagnosis_data', ['concave_points_worst'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_concavity_mean'), 'diagnosis_data', ['concavity_mean'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_concavity_se'), 'diagnosis_data', ['concavity_se'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_concavity_worst'), 'diagnosis_data', ['concavity_worst'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_diagnosis'), 'diagnosis_data', ['diagnosis'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_fractal_dimension_mean'), 'diagnosis_data', ['fractal_dimension_mean'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_fractal_dimension_se'), 'diagnosis_data', ['fractal_dimension_se'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_fractal_dimension_worst'), 'diagnosis_data', ['fractal_dimension_worst'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_perimeter_mean'), 'diagnosis_data', ['perimeter_mean'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_perimeter_se'), 'diagnosis_data', ['perimeter_se'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_perimeter_worst'), 'diagnosis_data', ['perimeter_worst'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_radius_mean'), 'diagnosis_data', ['radius_mean'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_radius_se'), 'diagnosis_data', ['radius_se'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_radius_worst'), 'diagnosis_data', ['radius_worst'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_smoothness_mean'), 'diagnosis_data', ['smoothness_mean'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_smoothness_se'), 'diagnosis_data', ['smoothness_se'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_smoothness_worst'), 'diagnosis_data', ['smoothness_worst'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_symmetry_mean'), 'diagnosis_data', ['symmetry_mean'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_symmetry_se'), 'diagnosis_data', ['symmetry_se'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_symmetry_worst'), 'diagnosis_data', ['symmetry_worst'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_texture_mean'), 'diagnosis_data', ['texture_mean'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_texture_se'), 'diagnosis_data', ['texture_se'], unique=False)
    op.create_index(op.f('ix_diagnosis_data_texture_worst'), 'diagnosis_data', ['texture_worst'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_data_texture_worst'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_texture_se'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_texture_mean'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_symmetry_worst'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_symmetry_se'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_symmetry_mean'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_smoothness_worst'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_smoothness_se'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_smoothness_mean'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_radius_worst'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_radius_se'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_radius_mean'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_perimeter_worst'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_perimeter_se'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_perimeter_mean'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_fractal_dimension_worst'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_fractal_dimension_se'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_fractal_dimension_mean'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_diagnosis'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_concavity_worst'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_concavity_se'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_concavity_mean'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_concave_points_worst'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_concave_points_se'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_concave_points_mean'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_compactness_worst'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_compactness_se'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_compactness_mean'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_area_worst'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_area_se'), table_name='diagnosis_data')
    op.drop_index(op.f('ix_diagnosis_data_area_mean'), table_name='diagnosis_data')
    op.drop_table('diagnosis_data')
    # ### end Alembic commands ###
